name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6

        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}

          script: |
            cd ~/frontend/FEMFrotend-main/FEMFrotend-main
            git pull origin master
            npm install
            pm2 restart frontend || pm2 start app.js --name frontend
